version: '3.8'

services:
  web:
    build:
      context: .
      target: web
    volumes:
      - ./:/app
    ports:
      - "4000:4000"
    depends_on:
      - db
  api:
    build:
      context: .
      target: api
    volumes:
      - ./:/app
    ports:
      - "4001:4001"
    depends_on:
      - db
  db:
    image: mariadb:10
    restart: always
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_ROOT_HOST: localhost
      MARIADB_USER: dejan
      MARIADB_PASSWORD: password
      MARIADB_DATABASE: go-stripe
    volumes:
      - db:/var/lib/mysql

volumes:
  db: